DeltasBookStoreApp/Models/BookDetails.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace DeltasBookStoreApp.Models
{
    public class BookDetails
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Book Name")]
        [Required(ErrorMessage = "Book Name can't be empty")]
        public string BookName { get; set; } = null!;

        [DisplayName("Author Name")]
        [Required(ErrorMessage = "Author Name can't be empty")]
        public string AuthorName { get; set; } = null!;

        [DisplayName("Publisher Name")]
        [Required(ErrorMessage = "Publisher Name can't be empty")]
        public string PublisherName { get; set; } = null!;

        [DisplayName("Published Date")]
        [Required(ErrorMessage = "Published Date can't be empty")]
        [DataType(DataType.Date, ErrorMessage = "Published Date is not valid")]
        public string PublishedDate { get; set; } = null!;

        [DisplayName("Price")]
        [Required(ErrorMessage = "Price can't be empty")]
        [DataType(DataType.Currency, ErrorMessage = "Price is not valid")]
        [Range(0.01, 10000, ErrorMessage = "Price must be greater than 0 and lesser than 10000")]
        public float Price { get; set; }

        [DisplayName("Book Description")]
        public string BookDescription { get; set; } = null!;

        [DisplayName("Total Copies Sold")]
        [Required(ErrorMessage = "Total Copies Sold can't be empty")]
        [DataType(DataType.Text)]
        public int TotalCopiesSold { get; set; }

        [DefaultValue("Y")]
        public string IsActive { get; set; } = "Y";
    }
}

DeltasBookStoreApp/Models/ErrorViewModel.cs
namespace DeltasBookStoreApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DeltasBookStoreApp/Controllers/BookDetailsController.cs
using DeltasBookStoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Text;

namespace DeltasBookStoreApp.Controllers
{
    public class BookDetailsController : Controller
    {
        Uri baseAddress = new Uri("http://localhost:5110/api");
        private readonly HttpClient _httpClient;

        public BookDetailsController()
        {
            _httpClient = new HttpClient();
            _httpClient.BaseAddress = baseAddress;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<BookDetails>? booksList = new List<BookDetails>();
            HttpResponseMessage httpResponseMessage = _httpClient.GetAsync(_httpClient.BaseAddress + "/BookDetails").Result;

            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string Data = httpResponseMessage.Content.ReadAsStringAsync().Result;
                booksList = JsonConvert.DeserializeObject<List<BookDetails>>(Data);
            }

            return View(booksList);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(BookDetails bookDetails)
        {
            try
            {
                string Data = JsonConvert.SerializeObject(bookDetails);
                StringContent content = new StringContent(Data, Encoding.UTF8, "application/json");
                HttpResponseMessage httpResponseMessage = _httpClient.PostAsync(_httpClient.BaseAddress + "/BookDetails", content).Result;

                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Book Details Added.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                TempData["errorMessage"] = "Error Occured While Saving, Please try again later.";
                return View();
            }

            return View();
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            BookDetails? bookDetails = new BookDetails();
            try
            {
                HttpResponseMessage httpResponseMessage = _httpClient.GetAsync(_httpClient.BaseAddress + "/BookDetails/" + Id).Result;

                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    string Data = httpResponseMessage.Content.ReadAsStringAsync().Result;
                    bookDetails = JsonConvert.DeserializeObject<BookDetails>(Data);
                }
            }
            catch (Exception)
            {
                TempData["errorMessage"] = "Error Occured While Fetching, Please try again later.";
                return View();
            }
            return View(bookDetails);
        }

        [HttpPost]
        public IActionResult Edit(BookDetails bookDetails)
        {
            try
            {
                string Data = JsonConvert.SerializeObject(bookDetails);
                StringContent content = new StringContent(Data, Encoding.UTF8, "application/json");
                HttpResponseMessage httpResponseMessage = _httpClient.PutAsync(_httpClient.BaseAddress + "/BookDetails/" + bookDetails.Id, content).Result;

                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Book Details Updated.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                TempData["errorMessage"] = "Error Occured While Updating, Please try again later.";
                return View();
            }

            return View();
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            BookDetails? bookDetails = new BookDetails();
            try
            {
                HttpResponseMessage httpResponseMessage = _httpClient.GetAsync(_httpClient.BaseAddress + "/BookDetails/" + Id).Result;

                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    string Data = httpResponseMessage.Content.ReadAsStringAsync().Result;
                    bookDetails = JsonConvert.DeserializeObject<BookDetails>(Data);
                }
            }
            catch (Exception)
            {
                TempData["errorMessage"] = "Error Occured While Fetching, Please try again later.";
                return View();
            }
            return View(bookDetails);
        }

        [HttpPost]
        public IActionResult Delete(BookDetails bookDetails)
        {
            try
            {
                HttpResponseMessage httpResponseMessage = _httpClient.DeleteAsync(_httpClient.BaseAddress + "/BookDetails/" + bookDetails.Id).Result;

                if (httpResponseMessage.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "Book Details Deleted.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                TempData["errorMessage"] = "Error Occured While Updating, Please try again later.";
                return View();
            }

            return View();
        }

        [HttpGet]
        public IActionResult DeletedBooks()
        {
            List<BookDetails>? booksList = new List<BookDetails>();
            HttpResponseMessage httpResponseMessage = _httpClient.GetAsync(_httpClient.BaseAddress + "/BookDetails/GetDeletedBookDetails").Result;

            if (httpResponseMessage.IsSuccessStatusCode)
            {
                string Data = httpResponseMessage.Content.ReadAsStringAsync().Result;
                booksList = JsonConvert.DeserializeObject<List<BookDetails>>(Data);
            }

            return View(booksList);
        }
    }
}

DeltasBookStoreApp/Controllers/HomeController.cs
using DeltasBookStoreApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DeltasBookStoreApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DeltasBookStoreApp/Views/BookDetails/Create.cshtml
@model DeltasBookStoreApp.Models.BookDetails

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BookDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @* <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="BookName" class="control-label"></label>
                <input asp-for="BookName" class="form-control" maxlength="100"/>
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" maxlength="100"/>
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label"></label>
                <input asp-for="PublisherName" class="form-control" maxlength="100"/>
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishedDate" class="control-label"></label>
                <input asp-for="PublishedDate" class="form-control" type="date"/>
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" type="number" maxlength="6"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookDescription" class="control-label"></label>
                <input asp-for="BookDescription" class="form-control" maxlength="100"/>
                <span asp-validation-for="BookDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalCopiesSold" class="control-label"></label>
                <input asp-for="TotalCopiesSold" class="form-control" type="number" maxlength="10"/>
                <span asp-validation-for="TotalCopiesSold" class="text-danger"></span>
            </div>
          @*  <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control"maxlength="1" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeltasBookStoreApp/Views/BookDetails/Delete.cshtml
@model DeltasBookStoreApp.Models.BookDetails

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BookDetails</h4>
    <hr />
    <dl class="row">
       @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>*@
       @* <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuthorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AuthorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublisherName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalCopiesSold)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalCopiesSold)
        </dd>
       @* <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsActive)
        </dd>*@
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DeltasBookStoreApp/Views/BookDetails/DeletedBooks.cshtml
@model IEnumerable<DeltasBookStoreApp.Models.BookDetails>

@{
    ViewData["Title"] = "DeletedBooks";
}

<h1>DeletedBooks</h1>

<p>
    @*<a asp-action="Create">Create New</a>*@
<a asp-action="Index">Back to List</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublisherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalCopiesSold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublisherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalCopiesSold)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
        </tr>
}
    </tbody>
</table>

DeltasBookStoreApp/Views/BookDetails/Edit.cshtml
@model DeltasBookStoreApp.Models.BookDetails

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BookDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @* <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="BookName" class="control-label"></label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger" maxlength="100"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorName" class="control-label"></label>
                <input asp-for="AuthorName" class="form-control" maxlength="100"/>
                <span asp-validation-for="AuthorName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label"></label>
                <input asp-for="PublisherName" class="form-control" maxlength="100"/>
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishedDate" class="control-label"></label>
                <input asp-for="PublishedDate" class="form-control" type="date"/>
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" maxlength="6"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookDescription" class="control-label"></label>
                <input asp-for="BookDescription" class="form-control" maxlength="100"/>
                <span asp-validation-for="BookDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalCopiesSold" class="control-label"></label>
                <input asp-for="TotalCopiesSold" class="form-control" maxlength="10" />
                <span asp-validation-for="TotalCopiesSold" class="text-danger"></span>
            </div>
         @*   <div class="form-group">
                <label asp-for="IsActive" class="control-label"></label>
                <input asp-for="IsActive" class="form-control" maxlength="1"/>
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeltasBookStoreApp/Views/BookDetails/Index.cshtml
@model IEnumerable<DeltasBookStoreApp.Models.BookDetails>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="DeletedBooks">Deleted Books</a>
</p>
<table class="table">
    <thead>
        <tr>@*
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AuthorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublisherName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalCopiesSold)
            </th>
          @*  <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           @* <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AuthorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublisherName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalCopiesSold)
            </td>
           @* <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
               @* @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  })
            </td>
        </tr>
}
    </tbody>
</table>

DeltasBookStoreApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DeltasBookStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeltasBookStoreApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeltasBookStoreApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DeltasBookStoreApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BookDetails" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
              @{
                var errorMessage = TempData["errorMessage"]?.ToString();
                var successMessage = TempData["successMessage"]?.ToString();
            }
            @if (!string.IsNullOrWhiteSpace(@successMessage))
            {
                <div class="alert alert-success">
                    <b>Success : </b>@successMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" arial-lable="Close"></button>
                </div>
            }
            else if (!string.IsNullOrWhiteSpace(@errorMessage))
            {
                <div class="alert alert-danger">
                    <b>Error : </b>@errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" arial-lable="Close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DeltasBookStoreApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
     <script src="~/js/Custom.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>